// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: orderForm.proto

package v1

import (
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CreateOrderFormRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateOrderFormRequest) Reset() {
	*x = CreateOrderFormRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orderForm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateOrderFormRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderFormRequest) ProtoMessage() {}

func (x *CreateOrderFormRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orderForm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderFormRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderFormRequest) Descriptor() ([]byte, []int) {
	return file_orderForm_proto_rawDescGZIP(), []int{0}
}

type CreateOrderFormReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateOrderFormReply) Reset() {
	*x = CreateOrderFormReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orderForm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateOrderFormReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderFormReply) ProtoMessage() {}

func (x *CreateOrderFormReply) ProtoReflect() protoreflect.Message {
	mi := &file_orderForm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderFormReply.ProtoReflect.Descriptor instead.
func (*CreateOrderFormReply) Descriptor() ([]byte, []int) {
	return file_orderForm_proto_rawDescGZIP(), []int{1}
}

type UpdateOrderFormRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateOrderFormRequest) Reset() {
	*x = UpdateOrderFormRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orderForm_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateOrderFormRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderFormRequest) ProtoMessage() {}

func (x *UpdateOrderFormRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orderForm_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderFormRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrderFormRequest) Descriptor() ([]byte, []int) {
	return file_orderForm_proto_rawDescGZIP(), []int{2}
}

type UpdateOrderFormReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateOrderFormReply) Reset() {
	*x = UpdateOrderFormReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orderForm_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateOrderFormReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderFormReply) ProtoMessage() {}

func (x *UpdateOrderFormReply) ProtoReflect() protoreflect.Message {
	mi := &file_orderForm_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderFormReply.ProtoReflect.Descriptor instead.
func (*UpdateOrderFormReply) Descriptor() ([]byte, []int) {
	return file_orderForm_proto_rawDescGZIP(), []int{3}
}

type DeleteOrderFormRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteOrderFormRequest) Reset() {
	*x = DeleteOrderFormRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orderForm_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteOrderFormRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrderFormRequest) ProtoMessage() {}

func (x *DeleteOrderFormRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orderForm_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrderFormRequest.ProtoReflect.Descriptor instead.
func (*DeleteOrderFormRequest) Descriptor() ([]byte, []int) {
	return file_orderForm_proto_rawDescGZIP(), []int{4}
}

type DeleteOrderFormReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteOrderFormReply) Reset() {
	*x = DeleteOrderFormReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orderForm_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteOrderFormReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrderFormReply) ProtoMessage() {}

func (x *DeleteOrderFormReply) ProtoReflect() protoreflect.Message {
	mi := &file_orderForm_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrderFormReply.ProtoReflect.Descriptor instead.
func (*DeleteOrderFormReply) Descriptor() ([]byte, []int) {
	return file_orderForm_proto_rawDescGZIP(), []int{5}
}

type GetOrderFormRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetOrderFormRequest) Reset() {
	*x = GetOrderFormRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orderForm_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrderFormRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderFormRequest) ProtoMessage() {}

func (x *GetOrderFormRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orderForm_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderFormRequest.ProtoReflect.Descriptor instead.
func (*GetOrderFormRequest) Descriptor() ([]byte, []int) {
	return file_orderForm_proto_rawDescGZIP(), []int{6}
}

func (x *GetOrderFormRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetOrderFormReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price uint64 `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *GetOrderFormReply) Reset() {
	*x = GetOrderFormReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orderForm_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrderFormReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderFormReply) ProtoMessage() {}

func (x *GetOrderFormReply) ProtoReflect() protoreflect.Message {
	mi := &file_orderForm_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderFormReply.ProtoReflect.Descriptor instead.
func (*GetOrderFormReply) Descriptor() ([]byte, []int) {
	return file_orderForm_proto_rawDescGZIP(), []int{7}
}

func (x *GetOrderFormReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetOrderFormReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetOrderFormReply) GetPrice() uint64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type ListOrderFormRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListOrderFormRequest) Reset() {
	*x = ListOrderFormRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orderForm_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListOrderFormRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrderFormRequest) ProtoMessage() {}

func (x *ListOrderFormRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orderForm_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrderFormRequest.ProtoReflect.Descriptor instead.
func (*ListOrderFormRequest) Descriptor() ([]byte, []int) {
	return file_orderForm_proto_rawDescGZIP(), []int{8}
}

type ListOrderFormReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListOrderFormReply) Reset() {
	*x = ListOrderFormReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orderForm_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListOrderFormReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrderFormReply) ProtoMessage() {}

func (x *ListOrderFormReply) ProtoReflect() protoreflect.Message {
	mi := &file_orderForm_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrderFormReply.ProtoReflect.Descriptor instead.
func (*ListOrderFormReply) Descriptor() ([]byte, []int) {
	return file_orderForm_proto_rawDescGZIP(), []int{9}
}

var File_orderForm_proto protoreflect.FileDescriptor

var file_orderForm_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x46, 0x6f, 0x72, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x06, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x18, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x46, 0x6f, 0x72, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x16, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x46, 0x6f, 0x72, 0x6d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x18, 0x0a, 0x16, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x46, 0x6f, 0x72, 0x6d, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x16, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x46, 0x6f, 0x72, 0x6d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x18, 0x0a, 0x16, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x46, 0x6f, 0x72, 0x6d, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x16, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x46, 0x6f, 0x72, 0x6d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x25, 0x0a,
	0x13, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x46, 0x6f, 0x72, 0x6d, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x4d, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x46, 0x6f, 0x72, 0x6d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x06, 0x52, 0x05, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x22, 0x16, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x46, 0x6f, 0x72, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x14, 0x0a, 0x12, 0x4c,
	0x69, 0x73, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x46, 0x6f, 0x72, 0x6d, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x32, 0xaa, 0x03, 0x0a, 0x09, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x46, 0x6f, 0x72, 0x6d, 0x12,
	0x4f, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x46, 0x6f,
	0x72, 0x6d, 0x12, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x46, 0x6f, 0x72, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x46, 0x6f, 0x72, 0x6d, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x4f, 0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x46,
	0x6f, 0x72, 0x6d, 0x12, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x46, 0x6f, 0x72, 0x6d, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x46, 0x6f, 0x72, 0x6d, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x4f, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x46, 0x6f, 0x72, 0x6d, 0x12, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x46, 0x6f, 0x72, 0x6d, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x46, 0x6f, 0x72, 0x6d, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x5f, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x46, 0x6f,
	0x72, 0x6d, 0x12, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x46, 0x6f, 0x72, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x46, 0x6f, 0x72, 0x6d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x17, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x11, 0x12, 0x0f, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x46, 0x6f, 0x72, 0x6d, 0x2f, 0x7b,
	0x69, 0x64, 0x7d, 0x12, 0x49, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x46, 0x6f, 0x72, 0x6d, 0x12, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x46, 0x6f, 0x72, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x46, 0x6f, 0x72, 0x6d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x1d,
	0x0a, 0x06, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x11, 0x67, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_orderForm_proto_rawDescOnce sync.Once
	file_orderForm_proto_rawDescData = file_orderForm_proto_rawDesc
)

func file_orderForm_proto_rawDescGZIP() []byte {
	file_orderForm_proto_rawDescOnce.Do(func() {
		file_orderForm_proto_rawDescData = protoimpl.X.CompressGZIP(file_orderForm_proto_rawDescData)
	})
	return file_orderForm_proto_rawDescData
}

var file_orderForm_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_orderForm_proto_goTypes = []interface{}{
	(*CreateOrderFormRequest)(nil), // 0: api.v1.CreateOrderFormRequest
	(*CreateOrderFormReply)(nil),   // 1: api.v1.CreateOrderFormReply
	(*UpdateOrderFormRequest)(nil), // 2: api.v1.UpdateOrderFormRequest
	(*UpdateOrderFormReply)(nil),   // 3: api.v1.UpdateOrderFormReply
	(*DeleteOrderFormRequest)(nil), // 4: api.v1.DeleteOrderFormRequest
	(*DeleteOrderFormReply)(nil),   // 5: api.v1.DeleteOrderFormReply
	(*GetOrderFormRequest)(nil),    // 6: api.v1.GetOrderFormRequest
	(*GetOrderFormReply)(nil),      // 7: api.v1.GetOrderFormReply
	(*ListOrderFormRequest)(nil),   // 8: api.v1.ListOrderFormRequest
	(*ListOrderFormReply)(nil),     // 9: api.v1.ListOrderFormReply
}
var file_orderForm_proto_depIdxs = []int32{
	0, // 0: api.v1.OrderForm.CreateOrderForm:input_type -> api.v1.CreateOrderFormRequest
	2, // 1: api.v1.OrderForm.UpdateOrderForm:input_type -> api.v1.UpdateOrderFormRequest
	4, // 2: api.v1.OrderForm.DeleteOrderForm:input_type -> api.v1.DeleteOrderFormRequest
	6, // 3: api.v1.OrderForm.GetOrderForm:input_type -> api.v1.GetOrderFormRequest
	8, // 4: api.v1.OrderForm.ListOrderForm:input_type -> api.v1.ListOrderFormRequest
	1, // 5: api.v1.OrderForm.CreateOrderForm:output_type -> api.v1.CreateOrderFormReply
	3, // 6: api.v1.OrderForm.UpdateOrderForm:output_type -> api.v1.UpdateOrderFormReply
	5, // 7: api.v1.OrderForm.DeleteOrderForm:output_type -> api.v1.DeleteOrderFormReply
	7, // 8: api.v1.OrderForm.GetOrderForm:output_type -> api.v1.GetOrderFormReply
	9, // 9: api.v1.OrderForm.ListOrderForm:output_type -> api.v1.ListOrderFormReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_orderForm_proto_init() }
func file_orderForm_proto_init() {
	if File_orderForm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_orderForm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateOrderFormRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orderForm_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateOrderFormReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orderForm_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateOrderFormRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orderForm_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateOrderFormReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orderForm_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteOrderFormRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orderForm_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteOrderFormReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orderForm_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrderFormRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orderForm_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrderFormReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orderForm_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListOrderFormRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orderForm_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListOrderFormReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_orderForm_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orderForm_proto_goTypes,
		DependencyIndexes: file_orderForm_proto_depIdxs,
		MessageInfos:      file_orderForm_proto_msgTypes,
	}.Build()
	File_orderForm_proto = out.File
	file_orderForm_proto_rawDesc = nil
	file_orderForm_proto_goTypes = nil
	file_orderForm_proto_depIdxs = nil
}
